#!/usr/bin/env python3
"""
抖音全自动转写 Pipeline v2.1
用法: python douyin_full_pipeline.py --url <抖音短链接>
可选: --model small|base|tiny|large (默认 small)
      --file <本地.mp4>  跳过下载，直接转写本地视频

依赖: yt-dlp + ffmpeg + openai-whisper + playwright (可选, 用于 cookie fallback)
"""

import sys
import os
import argparse
import subprocess
import re
import time
import shutil

# ── 路径常量 ──────────────────────────────────────────────
FFMPEG = r"G:\workspace\Infrastructure\bin\ffmpeg.exe"
WHISPER_CACHE = r"H:\workspace\.cache\whisper"
TEMP_DIR = r"G:\workspace\.temp_douyin"
COOKIES_FILE = os.path.join(TEMP_DIR, "cookies_playwright.txt")

os.makedirs(TEMP_DIR, exist_ok=True)

def log(msg):
    print(f"[pipeline] {msg}", flush=True)

def extract_video_id(url):
    """从各类抖音 URL 中提取视频 ID"""
    m = re.search(r"video/(\d+)", url)
    if m:
        return m.group(1)
    # Try resolving short link
    try:
        import requests
        r = requests.get(url, allow_redirects=True, timeout=10,
                        headers={"User-Agent": "Mozilla/5.0"})
        m = re.search(r"video/(\d+)", r.url)
        if m:
            return m.group(1)
    except:
        pass
    return None

def export_cookies_playwright(url):
    """用 Playwright 启动 headless Chromium 访问抖音页面并导出 cookies"""
    log("尝试用 Playwright 提取 cookies...")
    try:
        from playwright.sync_api import sync_playwright
    except ImportError:
        log("⚠️ playwright 未安装，跳过")
        return None

    try:
        with sync_playwright() as p:
            browser = p.chromium.launch(headless=True)
            context = browser.new_context(
                user_agent="Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 Chrome/120.0.0.0"
            )
            page = context.new_page()
            page.goto(url, wait_until="domcontentloaded", timeout=30000)
            time.sleep(3)  # 等待页面加载

            # Get cookies from context
            cookies = context.cookies()
            browser.close()

            if not cookies:
                log("⚠️ Playwright 未获取到 cookies")
                return None

            # Write Netscape format cookies file
            with open(COOKIES_FILE, "w", encoding="utf-8") as f:
                f.write("# Netscape HTTP Cookie File\n")
                f.write("# This file is generated by douyin_full_pipeline.py\n\n")
                for c in cookies:
                    domain = c.get("domain", "")
                    # Only keep douyin cookies
                    if "douyin" not in domain:
                        continue
                    flag = "TRUE" if domain.startswith(".") else "FALSE"
                    path = c.get("path", "/")
                    secure = "TRUE" if c.get("secure", False) else "FALSE"
                    expires = str(int(c.get("expires", 0)))
                    name = c.get("name", "")
                    value = c.get("value", "")
                    f.write(f"{domain}\t{flag}\t{path}\t{secure}\t{expires}\t{name}\t{value}\n")

            log(f"✓ Playwright 导出了 {len(cookies)} 个 cookies → {COOKIES_FILE}")
            return COOKIES_FILE

    except Exception as e:
        log(f"⚠️ Playwright cookie 提取失败: {e}")
        return None

def export_cookies_playwright_edge_profile():
    """用 Playwright + Edge 用户配置提取 cookies (解决 DPAPI 问题)"""
    log("尝试用 Playwright + Edge 用户配置提取 cookies...")
    try:
        from playwright.sync_api import sync_playwright
    except ImportError:
        log("⚠️ playwright 未安装，跳过")
        return None

    try:
        edge_profile = os.path.expanduser('~') + '/AppData/Local/Microsoft/Edge/User Data/Default'
        if not os.path.exists(edge_profile):
            log(f"⚠️ Edge 配置目录不存在: {edge_profile}")
            return None

        with sync_playwright() as p:
            browser = p.chromium.launch_persistent_context(
                user_data_dir=edge_profile,
                headless=True,
                channel='msedge',
                user_agent='Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 Chrome/120.0.0.0 Safari/537.36'
            )
            # 访问抖音首页获取 cookies
            page = browser.new_page()
            page.goto('https://www.douyin.com/', wait_until='domcontentloaded', timeout=30000)
            time.sleep(3)

            cookies = browser.cookies()
            browser.close()

            if not cookies:
                log("⚠️ 未获取到 cookies")
                return None

            # 写入 Netscape 格式
            COOKIES_FILE = os.path.join(TEMP_DIR, 'cookies_edge_profile.txt')
            with open(COOKIES_FILE, 'w', encoding='utf-8') as f:
                f.write('# Netscape HTTP Cookie File\n')
                for c in cookies:
                    if 'douyin' not in c.get('domain', ''):
                        continue
                    domain = c['domain']
                    flag = 'TRUE' if domain.startswith('.') else 'FALSE'
                    path = c.get('path', '/')
                    secure = 'TRUE' if c.get('secure', False) else 'FALSE'
                    expires = str(int(c.get('expires', 0)))
                    if expires == '0':
                        expires = '2147483647'
                    name = c.get('name', '')
                    value = c.get('value', '')
                    f.write(f'{domain}\t{flag}\t{path}\t{secure}\t{expires}\t{name}\t{value}\n')

            log(f"✓ Playwright 导出了 {len(cookies)} 个 cookies")
            has_ac = any('__ac_signature' in c['name'] for c in cookies)
            log(f"  __ac_signature: {'✅ 已获取' if has_ac else '❌ 未获取'}")
            return COOKIES_FILE

    except Exception as e:
        log(f"⚠️ Playwright cookie 提取失败: {e}")
        return None


def download_audio_playwright_mp4(url, output_dir):
    """用 Playwright + Edge 配置直接下载视频 (绕过 yt-dlp cookie 问题)"""
    log("尝试用 Playwright 直接下载视频...")
    import re, requests

    try:
        from playwright.sync_api import sync_playwright
    except ImportError:
        log("⚠️ playwright 未安装")
        return None

    try:
        edge_profile = os.path.expanduser('~') + '/AppData/Local/Microsoft/Edge/User Data/Default'
        with sync_playwright() as p:
            browser = p.chromium.launch_persistent_context(
                user_data_dir=edge_profile,
                headless=True,
                channel='msedge'
            )
            page = browser.new_page()
            page.goto(url, wait_until='domcontentloaded', timeout=30000)
            time.sleep(5)

            content = page.content()
            cookies = {c['name']: c['value'] for c in browser.cookies() if 'douyin' in c['domain']}
            browser.close()

        # 查找播放 URL
        play_urls = re.findall(r'https?://www\.douyin\.com/aweme/v1/play/[^\\"\\'\\\\s>]+', content)
        if not play_urls:
            log("❌ 未找到播放 URL")
            return None

        play_url = play_urls[0].replace('&amp;', '&')
        log(f"找到播放 URL，下载中...")

        headers = {'User-Agent': 'Mozilla/5.0', 'Referer': 'https://www.douyin.com/'}
        r = requests.get(play_url, headers=headers, cookies=cookies, stream=True, timeout=60)

        if r.status_code != 200:
            log(f"❌ 下载失败: HTTP {r.status_code}")
            return None

        # 提取视频 ID
        vid_m = re.search(r'video/(\d+)', url)
        vid = vid_m.group(1) if vid_m else 'video'
        ext = '.mp4' if 'video/mp4' in r.headers.get('Content-Type', '') else '.m4a'
        out_path = os.path.join(output_dir, f'{vid}{ext}')

        with open(out_path, 'wb') as f:
            f.write(r.content)

        size_mb = len(r.content) / 1024 / 1024
        log(f"✓ 视频下载完成: {size_mb:.1f}MB → {out_path}")
        return out_path

    except Exception as e:
        log(f"⚠️ Playwright 下载失败: {e}")
        return None


def download_audio_ytdlp(url, output_dir, cookies_file=None):
    """用 yt-dlp 下载音频"""
    log("下载音频中...")
    out_template = os.path.join(output_dir, "%(id)s.%(ext)s")

    cmd = [
        "yt-dlp",
        "--socket-timeout", "15",
        "--extract-audio",
        "--audio-format", "m4a",
        "--audio-quality", "0",
        "-o", out_template,
    ]
    if cookies_file:
        cmd += ["--cookies", cookies_file]
    else:
        cmd += ["--cookies-from-browser", "edge"]
    cmd.append(url)

    log(f"运行: yt-dlp ...")
    r = subprocess.run(cmd, capture_output=True, text=True, timeout=300)
    if r.returncode != 0:
        err = r.stderr[:300]
        log(f"⚠️ yt-dlp 下载失败: {err[:150]}")
        if "DPAPI" in err or "cookies" in err.lower():
            return "NEED_COOKIES"
        return None

    # 找出下载的文件
    for ext in [".m4a", ".mp4", ".webm"]:
        files = [f for f in os.listdir(output_dir) if f.endswith(ext) and not f.startswith(".")]
        if files:
            newest = max(files, key=lambda f: os.path.getmtime(os.path.join(output_dir, f)))
            log(f"✓ 下载完成: {newest}")
            return os.path.join(output_dir, newest)

    log("❌ 未找到下载的文件")
    return None

def extract_wav(media_path):
    """ffmpeg 转 WAV (16kHz, mono)"""
    if media_path.endswith(".wav"):
        return media_path

    log("提取音频为 WAV...")
    wav_path = media_path.rsplit(".", 1)[0] + ".wav"
    cmd = [
        FFMPEG, "-i", media_path,
        "-vn", "-acodec", "pcm_s16le",
        "-ar", "16000", "-ac", "1",
        "-y", wav_path
    ]
    r = subprocess.run(cmd, capture_output=True, text=True, timeout=300)
    if r.returncode != 0:
        log(f"❌ ffmpeg 转码失败: {r.stderr[:200]}")
        return None
    wav_size = os.path.getsize(wav_path) / 1024 / 1024
    log(f"✓ WAV 就绪: {wav_size:.1f}MB")
    return wav_path

def transcribe(wav_path, model_name="small"):
    """Whisper 转写"""
    log(f"加载模型: {model_name} (缓存: {WHISPER_CACHE})")
    import whisper
    model = whisper.load_model(model_name, download_root=WHISPER_CACHE)
    log("开始转写...")
    start = time.time()
    result = model.transcribe(wav_path, language="zh", verbose=False)
    elapsed = time.time() - start
    text = result["text"].strip()
    log(f"✓ 转写完成: {elapsed:.0f}s, {len(text)} 字")
    return text

def save_result(text, output_dir, vid):
    """保存转写文本"""
    txt_path = os.path.join(output_dir, f"{vid}.txt")
    with open(txt_path, "w", encoding="utf-8") as f:
        f.write(text)
    log(f"✓ 转写文本已保存: {txt_path}")
    return txt_path

def clean_temp(*paths):
    """清理临时文件"""
    for p in paths:
        if p and os.path.exists(p):
            os.remove(p)
    log("临时文件已清理")

def transcribe_local_file(file_path, model_name):
    """转写本地文件"""
    log(f"处理本地文件: {file_path}")
    vid = os.path.splitext(os.path.basename(file_path))[0]
    wav = extract_wav(file_path)
    if not wav:
        log("❌ 音频提取失败")
        return None, None
    text = transcribe(wav, model_name)
    if wav != file_path and file_path.endswith((".mp4", ".m4a")):
        clean_temp(wav)
    return text, vid

def main():
    parser = argparse.ArgumentParser(description="抖音全自动转写 Pipeline")
    parser.add_argument("--url", help="抖音短链接/完整链接")
    parser.add_argument("--file", help="本地视频/音频文件路径 (跳过下载)")
    parser.add_argument("--model", default="small",
                        choices=["tiny", "base", "small", "medium", "large"],
                        help="Whisper 模型 (默认 small)")
    args = parser.parse_args()

    model_name = args.model

    if args.file:
        # ── 本地文件模式 ──
        if not os.path.exists(args.file):
            log(f"❌ 文件不存在: {args.file}")
            sys.exit(1)
        text, vid = transcribe_local_file(args.file, model_name)
        if text is None:
            sys.exit(1)
        txt_path = save_result(text, TEMP_DIR, vid or "local_video")
        print(f"\n{'=' * 60}")
        print(f"📝 转写结果 ({len(text)} 字)")
        print('=' * 60)
        print(text)
        print('=' * 60)
        print(f"\n✅ 完成！转写文本: {txt_path}")
        return

    if not args.url:
        log("❌ 请提供 --url 或 --file")
        sys.exit(1)

    # ── URL 模式 ──
    url = args.url.strip()

    # 1. 获取视频 ID
    vid = extract_video_id(url)
    if vid:
        log(f"✓ 视频 ID: {vid}")
    else:
        log("❌ 无法解析视频 ID")
        sys.exit(1)

    # 确保使用完整抖音 URL
    if "douyin.com" not in url:
        url = f"https://www.douyin.com/video/{vid}"

    # 2. 尝试下载 (策略: yt-dlp → Playwright-cookies yt-dlp → Playwright 直接下载)
    result = download_audio_ytdlp(url, TEMP_DIR)
    if result == "NEED_COOKIES":
        log("yt-dlp cookie 失败，尝试策略二: Playwright cookies + yt-dlp...")
        cookies = export_cookies_playwright_edge_profile()
        if cookies:
            result = download_audio_ytdlp(url, TEMP_DIR, cookies)

    if result == "NEED_COOKIES" or not result:
        log("尝试策略三: Playwright + Edge 用户配置直接下载...")
        result = download_audio_playwright_mp4(url, TEMP_DIR)

    if not result:
        log("""
❌ 自动下载失败。

原因: yt-dlp 无法读取 Edge 浏览器 cookies (DPAPI 加密限制)。
     请手动下载视频后重新运行:

     1. 在 Edge 浏览器中打开视频链接
     2. 右键 → 另存为 (或使用下载工具)
     3. 运行:
        python douyin_full_pipeline.py --file "下载的视频路径"

     或转写已有的缓存文件.
""")
        # 检查是否有缓存文件可用
        cached = [f for f in os.listdir(TEMP_DIR) if f.endswith(('.mp4', '.m4a'))]
        if cached:
            log(f"提示: 临时目录有 {len(cached)} 个缓存文件，示例如下:")
            for f in cached[:3]:
                log(f"  {f}  ({os.path.getsize(os.path.join(TEMP_DIR, f))//1024//1024}MB)")
        sys.exit(1)

    media_path = result

    # 4. 转 WAV
    wav = extract_wav(media_path)
    if not wav:
        sys.exit(1)

    # 5. 转写
    try:
        text = transcribe(wav, model_name)
    except Exception as e:
        log(f"❌ 转写失败: {e}")
        clean_temp(media_path, wav)
        sys.exit(1)

    # 6. 保存
    txt_path = save_result(text, TEMP_DIR, vid)

    # 7. 输出
    print(f"\n{'=' * 60}")
    print(f"📝 转写结果 ({len(text)} 字)")
    print('=' * 60)
    print(text)
    print('=' * 60)

    # 8. 清理中间文件 (保留 txt)
    if wav and wav != media_path:
        clean_temp(wav)
    if media_path.endswith(".m4a"):
        clean_temp(media_path)

    print(f"\n✅ 完成！转写文本: {txt_path}")


if __name__ == "__main__":
    main()
